# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded
timezone: "Europe/Berlin"

# SEO settings
title: tomtone.github.io
description: "blogging about every day development stuff"
keywords: "web, development, magento, symfony, web technologies"
url: http://tomtone.github.io
baseurl: ""
# baseurl: ""

google_analytics: UA-39757199-2
repo: http://github.com/tomtone/tomtone.github.io
disqus_shortname: "thomasvgostomski"
disqus_site_shortname: "tomtone"

# Author settings
author:
  name      : Thomas von Gostomski
  job       : Webdeveloper
  bio       : "Magento Evangelist, Performace Enthusiast, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : info@von-gostomski.eu
  url       : http://nandomoreira.me
  github    : http://github.com/tomtone
  xing      : https://www.xing.com/profile/Thomas_vonGostomski

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]